import test from "node:test";
import assert from "node:assert/strict";
import {eligibility,validateRatings} from "./eligibility.mjs";
const now=new Date("2026-10-08T12:00:00Z");
const service=()=>({status:"completed",completedAt:"2026-10-07T12:00:00Z",verifiedByServer:true,independentEvidence:true,clientId:"client-1",professionalId:"pro-1",alreadyReviewed:false});
const client=()=>({id:"client-1",verifiedByServer:true});
const check=(s=service(),c=client(),ownerId="pro-1")=>eligibility({service:s,client:c,ownerId,now});
test("client verified and delivered service eligible",()=>assert.equal(check().ok,true));
test("visitor refused",()=>assert.equal(check(service(),{id:"visitor",verifiedByServer:true}).ok,false));
test("confirmed only refused",()=>assert.equal(check({...service(),status:"confirmed"}).reason,"not_completed"));
test("past checkout without independent evidence refused",()=>assert.equal(check({...service(),independentEvidence:false}).reason,"unverified_service"));
test("cancelled refused",()=>assert.equal(check({...service(),cancelled:true}).reason,"not_delivered"));
test("future completion refused",()=>assert.equal(check({...service(),completedAt:"2026-10-09T12:00:00Z"}).reason,"invalid_completion"));
test("unverified client refused",()=>assert.equal(check(service(),{id:"client-1",verifiedByServer:false}).reason,"unverified_client"));
test("owner self review refused",()=>assert.equal(check({...service(),clientId:"pro-1"}, {id:"pro-1",verifiedByServer:true}).reason,"self_review"));
test("duplicate refused",()=>assert.equal(check({...service(),alreadyReviewed:true}).reason,"already_reviewed"));
test("ratings valid and value-for-money separate",()=>assert.equal(validateRatings("loc",{quality:5,value_for_money:3,cleanliness:4}).ok,true));
test("missing criterion not scored zero",()=>assert.equal(validateRatings("loc",{quality:5}).ok,true));
test("unknown criterion refused",()=>assert.equal(validateRatings("loc",{driving_safety:5}).ok,false));
test("invalid stars refused",()=>assert.equal(validateRatings("loc",{quality:0}).ok,false));
