import test from "node:test";
import assert from "node:assert/strict";
import {receivePrivateFeedback} from "./private-receiver.mjs";
const id="c3a48bfa-9d2e-4f0a-8b1e-84989a9b4f7a";
const body={contractVersion:"trust_feedback_v12",listingId:id,overallRating:4,cleanliness:5,comment:"Très bien",stayedHere:true,publicationConsent:false};
const req={method:"POST",contentType:"application/json",bodyBytes:230,body};
const setup=()=>{let writes=[];return {writes,services:{enabled:true,checkBot:async()=>true,checkRateLimit:async()=>true,lookupActiveListing:async()=>true,storePrivate:async record=>{writes.push(record);return true}}}};
test("disabled denies and never writes",async()=>{const s=setup();s.services.enabled=false;assert.equal((await receivePrivateFeedback(req,s.services)).status,503);assert.equal(s.writes.length,0)});
test("valid request stores only private moderation record",async()=>{const s=setup();const out=await receivePrivateFeedback(req,s.services);assert.equal(out.status,202);assert.equal(s.writes.length,1);assert.equal(s.writes[0].moderation_status,"received");assert.equal(s.writes[0].stay_verified,false);assert.equal(s.writes[0].publication_consent,false);assert.equal("published" in s.writes[0],false)});
test("unknown listing cannot write",async()=>{const s=setup();s.services.lookupActiveListing=async()=>false;assert.equal((await receivePrivateFeedback(req,s.services)).status,400);assert.equal(s.writes.length,0)});
test("bot denied",async()=>{const s=setup();s.services.checkBot=async()=>false;assert.equal((await receivePrivateFeedback(req,s.services)).status,400);assert.equal(s.writes.length,0)});
test("quota denied",async()=>{const s=setup();s.services.checkRateLimit=async()=>false;assert.equal((await receivePrivateFeedback(req,s.services)).status,400);assert.equal(s.writes.length,0)});
test("storage failure is unavailable",async()=>{const s=setup();s.services.storePrivate=async()=>false;assert.equal((await receivePrivateFeedback(req,s.services)).status,503)});
test("missing adapters denied",async()=>assert.equal((await receivePrivateFeedback(req,{enabled:true})).status,503));
test("malformed rating denied",async()=>{const s=setup();assert.equal((await receivePrivateFeedback({...req,body:{...body,overallRating:9}},s.services)).status,400);assert.equal(s.writes.length,0)});
test("non-uuid listing denied",async()=>{const s=setup();assert.equal((await receivePrivateFeedback({...req,body:{...body,listingId:"example"}},s.services)).status,400);assert.equal(s.writes.length,0)});
test("unconsented publication still stores privately",async()=>{const s=setup();await receivePrivateFeedback(req,s.services);assert.equal(s.writes[0].publication_consent,false)});
test("throws closed without details",async()=>{const s=setup();s.services.storePrivate=async()=>{throw Error("secret")};const out=await receivePrivateFeedback(req,s.services);assert.equal(out.status,503);assert.equal(JSON.stringify(out).includes("secret"),false)});
test("oversized request denied",async()=>{const s=setup();assert.equal((await receivePrivateFeedback({...req,bodyBytes:5000},s.services)).status,400);assert.equal(s.writes.length,0)});
